# Question 1 - Extracting Tesla Stock Data Using yfinance

In [1]:
import yfinance as yf
import pandas as pd

In [2]:
tesla=yf.Ticker("TSLA")

In [3]:
tesla_stock_data=tesla.history(period="max")

In [4]:
tesla_stock_data.reset_index(inplace=True)

In [6]:
tesla_stock_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

# Question 2 - Extracting Tesla Revenue Data Using Webscraping

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [8]:
url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm'
html_data=requests.get(url).text

In [9]:
soup = BeautifulSoup(html_data, "html5lib")
tesla_revenue_data = pd.DataFrame(columns=["Date", "Revenue"])

In [13]:
table = soup.findAll("table",{"class":"historical_data_table table"})
my_tab=table[1]

In [ ]:
for row in my_tab.find('tbody').find_all('tr'):
    col=row.find_all('td')
    date=col[0]
    revenue=col[1]
    tesla_revenue_data=tesla_revenue_data.append({"Date":date,"Revenue":revenue},ignore_index=True)

In [15]:
tesla_revenue_data.tail()

            Date Revenue
62  [2010-06-30]   [$28]
63  [2010-03-31]   [$21]
64  [2009-12-31]      []
65  [2009-09-30]   [$46]
66  [2009-06-30]   [$27]

# Question 3 - Extracting GameStop Stock Data Using yfinance

In [26]:
game_stop=yf.Ticker("GME")

In [27]:
gamestop_data=game_stop.history(period="max")

In [28]:
gamestop_data.reset_index(inplace=True)

In [29]:
gamestop_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620129,1.693350,1.603296,1.691667,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

# Question 4 - Extracting GameStop Revenue Data Using Webscraping

In [30]:
url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html'
html_data2=requests.get(url).text

In [31]:
soup=BeautifulSoup(html_data2,'html5lib')
gme_revenue=pd.DataFrame(columns=["Date", "Revenue"])

In [32]:
table = soup.findAll("table",{"class":"historical_data_table table"})
my_tab=table[1]

In [33]:
for row in my_tab.find('tbody').find_all('tr'):
    col=row.find_all('td')
    date=col[0]
    revenue=col[1]
    gme_revenue=gme_revenue.append({"Date":date,"Revenue":revenue},ignore_index=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4008\108114067.py:5: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

In [34]:
gme_revenue.tail()

            Date   Revenue
57  [2006-01-31]  [$1,667]
58  [2005-10-31]    [$534]
59  [2005-07-31]    [$416]
60  [2005-04-30]    [$475]
61  [2005-01-31]    [$709]

# Question 5 - Tesla Stock and Revenue Dashboard

In [22]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [23]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data.Date, infer_datetime_format=True), y=stock_data.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data.Date, infer_datetime_format=True), y=revenue_data.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

In [ ]:
make_graph(tesla_stock_data,tesla_revenue_data,'Tesla')

In [35]:
make_graph(gamestop_data,gme_revenue,'Tesla')

TypeError: <class 'bs4.element.Tag'> is not convertible to datetime